apiVersion: v1
kind: Service
metadata:
  name: argo-lb-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.203
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  ports:
    - port: 80
      targetPort: 80
