# Main directory with argo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-entry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wojtacha/cluster.proxima-centauri.git
    targetRevision: master
    path: cluster/nginx-entry
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: v0.15.2
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-storage-class
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    path: deploy/chart/local-path-provisioner/
    targetRevision: v0.0.31
    helm:
      values: |
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /data
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: cloud-pg
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/wojtacha/cluster.proxima-centauri.git
#     targetRevision: master
#     path: cluster/pg-cloudnative
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
