apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: immich
  name: pvc-immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 180Gi
---
apiVersion: v1
kind: Service
metadata:
  name: immich-lb-svc
  namespace: immich
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.208
  selector:
    app.kubernetes.io/instance: immich-package
    app.kubernetes.io/name: server
  ports:
    - port: 80
      targetPort: 2283
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: immich
spec:
  ports:
    - port: 3003
      targetPort: 3003
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: test-service
  namespace: immich
subsets:
  - addresses:
      - ip: 192.168.100.244
    ports:
      - port: 3003
