apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: immich
  name: pvc-immich-200
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi
