apiVersion: v1
data:
  password: aW1taWNo
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2025-07-24T20:31:58Z"
  name: immich-db-secret
  namespace: prometheus
  resourceVersion: "1977202933"
  uid: 531c22f4-21b7-4b6a-8841-d7b0e6b6d28a
type: Opaque
