apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: local-storage-class
data:
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/data"]
        }
      ]
    }
