---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: test
spec:
  ports:
    - port: 8080
      targetPort: 8080
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: test-service
  namespace: test
subsets:
  - addresses:
      - ip: 192.168.100.244
    ports:
      - port: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: test
spec:
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
