apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-lan
spec:
  addresses:
    - 192.168.100.200-192.168.100.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local-lan-l2adv
spec: {}
