apiVersion: v1
data:
  index.html: |
    <html>
      <head><title>Welcome</title></head>
      <body style="text-align:center; font-family:sans-serif;">
        <h1 style="color:steelblue;">Hello from Nginx on Kubernetes!</h1>
        <p>This is a nice static HTML site.</p>
      </body>
    </html>
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: default
