apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: nginx-pod
  namespace: default
spec:
  containers:
    - image: nginx:latest
      imagePullPolicy: Always
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources: {}
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-d5wgq
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
  volumes:
    - configMap:
        defaultMode: 420
        name: nginx-html
      name: html
