apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.203
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
